#include "../INCLUDE/system.h"

extern int	main();


void sleep (u32 delay){
	for (u32 i = 0; i < delay; i++)
		for (u32 j = 0; j < delay; j++)
			for (u32 k = 0; k < delay; k++);
}

void	draw_weird(){
	while (1){
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("    _____                           o o o o o                                   ");
	put_str("  __|[_]|__ ___________ _______    ____      o                                  ");
	put_str(" |[] [] []| [] [] [] [] [_____(__  ][]]_n_n__][.                                ");
	put_str("_|________|_[_________]_[________]_|__|________)<                               ");
	put_str(" oo    oo 'oo      oo ' oo    oo 'oo 0000---oo\\_                                ");
	put_str("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	sleep(400);
	set_cursor(0, 0);
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                      o o o                                     ");
	put_str("      _____                                 o o                                 ");
	put_str("    __|[_]|__ ___________ _______    ____      o                                ");
	put_str("   |[] [] []| [] [] [] [] [_____(__  ][]]_n_n__][.                              ");
	put_str("  _|________|_[_________]_[________]_|__|________)<                             ");
	put_str("   oo    oo 'oo      oo ' oo    oo 'oo 0000---oo\\_                              ");
	put_str("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	sleep(400);
	set_cursor(0, 0);
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                        o o o o                                 ");
	put_str("        _____                                   o                               ");
	put_str("      __|[_]|__ ___________ _______    ____      o                              ");
	put_str("     |[] [] []| [] [] [] [] [_____(__  ][]]_n_n__][.                            ");
	put_str("    _|________|_[_________]_[________]_|__|________)<                           ");
	put_str("     oo    oo 'oo      oo ' oo    oo 'oo 0000---oo\\_                            ");
	put_str("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	sleep(400);
	set_cursor(0, 0);
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                          o o                                   ");
	put_str("                                              o o                               ");
	put_str("          _____                                   o                             ");
	put_str("        __|[_]|__ ___________ _______    ____      o                            ");
	put_str("       |[] [] []| [] [] [] [] [_____(__  ][]]_n_n__][.                          ");
	put_str("      _|________|_[_________]_[________]_|__|________)<                         ");
	put_str("       oo    oo 'oo      oo ' oo    oo 'oo 0000---oo\\_                          ");
	put_str("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	sleep(400);
	set_cursor(0, 0);
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                            o o                                 ");
	put_str("                                                o o                             ");
	put_str("            _____                                   o                           ");
	put_str("          __|[_]|__ ___________ _______    ____      o                          ");
	put_str("         |[] [] []| [] [] [] [] [_____(__  ][]]_n_n__][.                        ");
	put_str("        _|________|_[_________]_[________]_|__|________)<                       ");
	put_str("         oo    oo 'oo      oo ' oo    oo 'oo 0000---oo\\_                        ");
	put_str("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	sleep(400);
	set_cursor(0, 0);
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                        |                                                       ");
	put_str("                                            o o                                 ");
	put_str("                                                o o                             ");
	put_str("            _____                                   o                           ");
	put_str("          __|[_]|__ ___________ _______    ____      o                          ");
	put_str("         |[] [] []| [] [] [] [] [_____(__  ][]]_n_n__][.                        ");
	put_str("        _|________|_[_________]_[________]_|__|________)<                       ");
	put_str("         oo    oo 'oo      oo ' oo    oo 'oo 0000---oo\\_                        ");
	put_str("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	sleep(400);
	set_cursor(0, 0);
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                        |                                                       ");
	put_str("                        |                   o o                                 ");
	put_str("                                                o o                             ");
	put_str("            _____                                   o                           ");
	put_str("          __|[_]|__ ___________ _______    ____      o                          ");
	put_str("         |[] [] []| [] [] [] [] [_____(__  ][]]_n_n__][.                        ");
	put_str("        _|________|_[_________]_[________]_|__|________)<                       ");
	put_str("         oo    oo 'oo      oo ' oo    oo 'oo 0000---oo\\_                        ");
	put_str("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	sleep(400);
	set_cursor(0, 0);
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                        |                                                       ");
	put_str("                        |                   o o                                 ");
	put_str("                        |                       o o                             ");
	put_str("            _____                                   o                           ");
	put_str("          __|[_]|__ ___________ _______    ____      o                          ");
	put_str("         |[] [] []| [] [] [] [] [_____(__  ][]]_n_n__][.                        ");
	put_str("        _|________|_[_________]_[________]_|__|________)<                       ");
	put_str("         oo    oo 'oo      oo ' oo    oo 'oo 0000---oo\\_                        ");
	put_str("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	sleep(400);
	set_cursor(0, 0);
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                        |                                                       ");
	put_str("                        |                   o o                                 ");
	put_str("                        |/                      o o                             ");
	put_str("            _____                                   o                           ");
	put_str("          __|[_]|__ ___________ _______    ____      o                          ");
	put_str("         |[] [] []| [] [] [] [] [_____(__  ][]]_n_n__][.                        ");
	put_str("        _|________|_[_________]_[________]_|__|________)<                       ");
	put_str("         oo    oo 'oo      oo ' oo    oo 'oo 0000---oo\\_                        ");
	put_str("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	sleep(400);
	set_cursor(0, 0);
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                        |                                                       ");
	put_str("                        |                   o o                                 ");
	put_str("                       \\|/                      o o                             ");
	put_str("            _____                                   o                           ");
	put_str("          __|[_]|__ ___________ _______    ____      o                          ");
	put_str("         |[] [] []| [] [] [] [] [_____(__  ][]]_n_n__][.                        ");
	put_str("        _|________|_[_________]_[________]_|__|________)<                       ");
	put_str("         oo    oo 'oo      oo ' oo    oo 'oo 0000---oo\\_                        ");
	put_str("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	sleep(400);
	set_cursor(0, 0);
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                   T                                                            ");
	put_str("                        |                                                       ");
	put_str("                        |                   o o                                 ");
	put_str("                       \\|/                      o o                             ");
	put_str("            _____                                   o                           ");
	put_str("          __|[_]|__ ___________ _______    ____      o                          ");
	put_str("         |[] [] []| [] [] [] [] [_____(__  ][]]_n_n__][.                        ");
	put_str("        _|________|_[_________]_[________]_|__|________)<                       ");
	put_str("         oo    oo 'oo      oo ' oo    oo 'oo 0000---oo\\_                        ");
	put_str("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	sleep(400);
	set_cursor(0, 0);
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                   TR                                                           ");
	put_str("                        |                                                       ");
	put_str("                        |                   o o                                 ");
	put_str("                       \\|/                      o o                             ");
	put_str("            _____                                   o                           ");
	put_str("          __|[_]|__ ___________ _______    ____      o                          ");
	put_str("         |[] [] []| [] [] [] [] [_____(__  ][]]_n_n__][.                        ");
	put_str("        _|________|_[_________]_[________]_|__|________)<                       ");
	put_str("         oo    oo 'oo      oo ' oo    oo 'oo 0000---oo\\_                        ");
	put_str("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	sleep(400);
	set_cursor(0, 0);
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                   TRA                                                          ");
	put_str("                        |                                                       ");
	put_str("                        |                   o o                                 ");
	put_str("                       \\|/                      o o                             ");
	put_str("            _____                                   o                           ");
	put_str("          __|[_]|__ ___________ _______    ____      o                          ");
	put_str("         |[] [] []| [] [] [] [] [_____(__  ][]]_n_n__][.                        ");
	put_str("        _|________|_[_________]_[________]_|__|________)<                       ");
	put_str("         oo    oo 'oo      oo ' oo    oo 'oo 0000---oo\\_                        ");
	put_str("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	sleep(400);
	set_cursor(0, 0);
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                   TRAI                                                         ");
	put_str("                        |                                                       ");
	put_str("                        |                   o o                                 ");
	put_str("                       \\|/                      o o                             ");
	put_str("            _____                                   o                           ");
	put_str("          __|[_]|__ ___________ _______    ____      o                          ");
	put_str("         |[] [] []| [] [] [] [] [_____(__  ][]]_n_n__][.                        ");
	put_str("        _|________|_[_________]_[________]_|__|________)<                       ");
	put_str("         oo    oo 'oo      oo ' oo    oo 'oo 0000---oo\\_                        ");
	put_str("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	sleep(400);
	set_cursor(0, 0);
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                   TRAIN                                                        ");
	put_str("                        |                                                       ");
	put_str("                        |                   o o                                 ");
	put_str("                       \\|/                      o o                             ");
	put_str("            _____                                   o                           ");
	put_str("          __|[_]|__ ___________ _______    ____      o                          ");
	put_str("         |[] [] []| [] [] [] [] [_____(__  ][]]_n_n__][.                        ");
	put_str("        _|________|_[_________]_[________]_|__|________)<                       ");
	put_str("         oo    oo 'oo      oo ' oo    oo 'oo 0000---oo\\_                        ");
	put_str("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	sleep(400);
	set_cursor(0, 0);
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                   TRAIN O                                                      ");
	put_str("                        |                                                       ");
	put_str("                        |                   o o                                 ");
	put_str("                       \\|/                      o o                             ");
	put_str("            _____                                   o                           ");
	put_str("          __|[_]|__ ___________ _______    ____      o                          ");
	put_str("         |[] [] []| [] [] [] [] [_____(__  ][]]_n_n__][.                        ");
	put_str("        _|________|_[_________]_[________]_|__|________)<                       ");
	put_str("         oo    oo 'oo      oo ' oo    oo 'oo 0000---oo\\_                        ");
	put_str("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	sleep(400);
	set_cursor(0, 0);
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                   TRAIN OF                                                     ");
	put_str("                        |                                                       ");
	put_str("                        |                   o o                                 ");
	put_str("                       \\|/                      o o                             ");
	put_str("            _____                                   o                           ");
	put_str("          __|[_]|__ ___________ _______    ____      o                          ");
	put_str("         |[] [] []| [] [] [] [] [_____(__  ][]]_n_n__][.                        ");
	put_str("        _|________|_[_________]_[________]_|__|________)<                       ");
	put_str("         oo    oo 'oo      oo ' oo    oo 'oo 0000---oo\\_                        ");
	put_str("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	sleep(400);
	set_cursor(0, 0);
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                   TRAIN OF N                                                   ");
	put_str("                        |                                                       ");
	put_str("                        |                   o o                                 ");
	put_str("                       \\|/                      o o                             ");
	put_str("            _____                                   o                           ");
	put_str("          __|[_]|__ ___________ _______    ____      o                          ");
	put_str("         |[] [] []| [] [] [] [] [_____(__  ][]]_n_n__][.                        ");
	put_str("        _|________|_[_________]_[________]_|__|________)<                       ");
	put_str("         oo    oo 'oo      oo ' oo    oo 'oo 0000---oo\\_                        ");
	put_str("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	sleep(750);
	set_cursor(0, 0);
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                   TRAIN OF NE                                                  ");
	put_str("                        |                                                       ");
	put_str("                        |                   o o                                 ");
	put_str("                       \\|/                      o o                             ");
	put_str("            _____                                   o                           ");
	put_str("          __|[_]|__ ___________ _______    ____      o                          ");
	put_str("         |[] [] []| [] [] [] [] [_____(__  ][]]_n_n__][.                        ");
	put_str("        _|________|_[_________]_[________]_|__|________)<                       ");
	put_str("         oo    oo 'oo      oo ' oo    oo 'oo 0000---oo\\_                        ");
	put_str("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	sleep(250);
	set_cursor(0, 0);
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                   TRAIN OF NEV                                                 ");
	put_str("                        |                                                       ");
	put_str("                        |                   o o                                 ");
	put_str("                       \\|/                      o o                             ");
	put_str("            _____                                   o                           ");
	put_str("          __|[_]|__ ___________ _______    ____      o                          ");
	put_str("         |[] [] []| [] [] [] [] [_____(__  ][]]_n_n__][.                        ");
	put_str("        _|________|_[_________]_[________]_|__|________)<                       ");
	put_str("         oo    oo 'oo      oo ' oo    oo 'oo 0000---oo\\_                        ");
	put_str("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	sleep(250);
	set_cursor(0, 0);
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                   TRAIN OF NEVE                                                ");
	put_str("                        |                                                       ");
	put_str("                        |                   o o                                 ");
	put_str("                       \\|/                      o o                             ");
	put_str("            _____                                   o                           ");
	put_str("          __|[_]|__ ___________ _______    ____      o                          ");
	put_str("         |[] [] []| [] [] [] [] [_____(__  ][]]_n_n__][.                        ");
	put_str("        _|________|_[_________]_[________]_|__|________)<                       ");
	put_str("         oo    oo 'oo      oo ' oo    oo 'oo 0000---oo\\_                        ");
	put_str("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	sleep(250);
	set_cursor(0, 0);
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                   TRAIN OF NEVER                                               ");
	put_str("                        |                                                       ");
	put_str("                        |                   o o                                 ");
	put_str("                       \\|/                      o o                             ");
	put_str("            _____                                   o                           ");
	put_str("          __|[_]|__ ___________ _______    ____      o                          ");
	put_str("         |[] [] []| [] [] [] [] [_____(__  ][]]_n_n__][.                        ");
	put_str("        _|________|_[_________]_[________]_|__|________)<                       ");
	put_str("         oo    oo 'oo      oo ' oo    oo 'oo 0000---oo\\_                        ");
	put_str("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	sleep(250);
	set_cursor(0, 0);
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                   TRAIN OF NEVER G                                             ");
	put_str("                        |                                                       ");
	put_str("                        |                   o o                                 ");
	put_str("                       \\|/                      o o                             ");
	put_str("            _____                                   o                           ");
	put_str("          __|[_]|__ ___________ _______    ____      o                          ");
	put_str("         |[] [] []| [] [] [] [] [_____(__  ][]]_n_n__][.                        ");
	put_str("        _|________|_[_________]_[________]_|__|________)<                       ");
	put_str("         oo    oo 'oo      oo ' oo    oo 'oo 0000---oo\\_                        ");
	put_str("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	sleep(250);
	set_cursor(0, 0);
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                   TRAIN OF NEVER GO                                            ");
	put_str("                        |                                                       ");
	put_str("                        |                   o o                                 ");
	put_str("                       \\|/                      o o                             ");
	put_str("            _____                                   o                           ");
	put_str("          __|[_]|__ ___________ _______    ____      o                          ");
	put_str("         |[] [] []| [] [] [] [] [_____(__  ][]]_n_n__][.                        ");
	put_str("        _|________|_[_________]_[________]_|__|________)<                       ");
	put_str("         oo    oo 'oo      oo ' oo    oo 'oo 0000---oo\\_                        ");
	put_str("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	sleep(250);
	set_cursor(0, 0);
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                   TRAIN OF NEVER GON                                           ");
	put_str("                        |                                                       ");
	put_str("                        |                   o o                                 ");
	put_str("                       \\|/                      o o                             ");
	put_str("            _____                                   o                           ");
	put_str("          __|[_]|__ ___________ _______    ____      o                          ");
	put_str("         |[] [] []| [] [] [] [] [_____(__  ][]]_n_n__][.                        ");
	put_str("        _|________|_[_________]_[________]_|__|________)<                       ");
	put_str("         oo    oo 'oo      oo ' oo    oo 'oo 0000---oo\\_                        ");
	put_str("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	sleep(250);
	set_cursor(0, 0);
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                   TRAIN OF NEVER GONN                                          ");
	put_str("                        |                                                       ");
	put_str("                        |                   o o                                 ");
	put_str("                       \\|/                      o o                             ");
	put_str("            _____                                   o                           ");
	put_str("          __|[_]|__ ___________ _______    ____      o                          ");
	put_str("         |[] [] []| [] [] [] [] [_____(__  ][]]_n_n__][.                        ");
	put_str("        _|________|_[_________]_[________]_|__|________)<                       ");
	put_str("         oo    oo 'oo      oo ' oo    oo 'oo 0000---oo\\_                        ");
	put_str("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	sleep(250);
	set_cursor(0, 0);
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                   TRAIN OF NEVER GONNA                                         ");
	put_str("                        |                                                       ");
	put_str("                        |                   o o                                 ");
	put_str("                       \\|/                      o o                             ");
	put_str("            _____                                   o                           ");
	put_str("          __|[_]|__ ___________ _______    ____      o                          ");
	put_str("         |[] [] []| [] [] [] [] [_____(__  ][]]_n_n__][.                        ");
	put_str("        _|________|_[_________]_[________]_|__|________)<                       ");
	put_str("         oo    oo 'oo      oo ' oo    oo 'oo 0000---oo\\_                        ");
	put_str("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	sleep(250);
	set_cursor(0, 0);
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                   TRAIN OF NEVER GONNA                                         ");
	put_str("                        |                                                       ");
	put_str("                        |                   o o                                 ");
	put_str("                       \\|/                      o o                             ");
	put_str("            _____                                   o                           ");
	put_str("          __|[_]|__ ___________ _______    ____      o                          ");
	put_str("         |[] [] []| [] [] [] [] [_____(__  ][]]_n_n__][.                        ");
	put_str("        _|________|_[_________]_[________]_|__|________)<                       ");
	put_str("         oo    oo 'oo      oo ' oo    oo 'oo 0000---oo\\_                        ");
	put_str("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	sleep(250);
	set_cursor(0, 0);
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                   TRAIN OF NEVER GONNA G                                       ");
	put_str("                        |                                                       ");
	put_str("                        |                   o o                                 ");
	put_str("                       \\|/                      o o                             ");
	put_str("            _____                                   o                           ");
	put_str("          __|[_]|__ ___________ _______    ____      o                          ");
	put_str("         |[] [] []| [] [] [] [] [_____(__  ][]]_n_n__][.                        ");
	put_str("        _|________|_[_________]_[________]_|__|________)<                       ");
	put_str("         oo    oo 'oo      oo ' oo    oo 'oo 0000---oo\\_                        ");
	put_str("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	sleep(250);
	set_cursor(0, 0);
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                   TRAIN OF NEVER GONNA GI                                      ");
	put_str("                        |                                                       ");
	put_str("                        |                   o o                                 ");
	put_str("                       \\|/                      o o                             ");
	put_str("            _____                                   o                           ");
	put_str("          __|[_]|__ ___________ _______    ____      o                          ");
	put_str("         |[] [] []| [] [] [] [] [_____(__  ][]]_n_n__][.                        ");
	put_str("        _|________|_[_________]_[________]_|__|________)<                       ");
	put_str("         oo    oo 'oo      oo ' oo    oo 'oo 0000---oo\\_                        ");
	put_str("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	sleep(250);
	set_cursor(0, 0);
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                   TRAIN OF NEVER GONNA GIV                                     ");
	put_str("                        |                                                       ");
	put_str("                        |                   o o                                 ");
	put_str("                       \\|/                      o o                             ");
	put_str("            _____                                   o                           ");
	put_str("          __|[_]|__ ___________ _______    ____      o                          ");
	put_str("         |[] [] []| [] [] [] [] [_____(__  ][]]_n_n__][.                        ");
	put_str("        _|________|_[_________]_[________]_|__|________)<                       ");
	put_str("         oo    oo 'oo      oo ' oo    oo 'oo 0000---oo\\_                        ");
	put_str("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	sleep(250);
	set_cursor(0, 0);
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                   TRAIN OF NEVER GONNA GIVE                                    ");
	put_str("                        |                                                       ");
	put_str("                        |                   o o                                 ");
	put_str("                       \\|/                      o o                             ");
	put_str("            _____                                   o                           ");
	put_str("          __|[_]|__ ___________ _______    ____      o                          ");
	put_str("         |[] [] []| [] [] [] [] [_____(__  ][]]_n_n__][.                        ");
	put_str("        _|________|_[_________]_[________]_|__|________)<                       ");
	put_str("         oo    oo 'oo      oo ' oo    oo 'oo 0000---oo\\_                        ");
	put_str("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	sleep(250);
	set_cursor(0, 0);
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                   TRAIN OF NEVER GONNA GIVE Y                                  ");
	put_str("                        |                                                       ");
	put_str("                        |                   o o                                 ");
	put_str("                       \\|/                      o o                             ");
	put_str("            _____                                   o                           ");
	put_str("          __|[_]|__ ___________ _______    ____      o                          ");
	put_str("         |[] [] []| [] [] [] [] [_____(__  ][]]_n_n__][.                        ");
	put_str("        _|________|_[_________]_[________]_|__|________)<                       ");
	put_str("         oo    oo 'oo      oo ' oo    oo 'oo 0000---oo\\_                        ");
	put_str("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	sleep(250);
	set_cursor(0, 0);
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                   TRAIN OF NEVER GONNA GIVE YO                                 ");
	put_str("                        |                                                       ");
	put_str("                        |                   o o                                 ");
	put_str("                       \\|/                      o o                             ");
	put_str("            _____                                   o                           ");
	put_str("          __|[_]|__ ___________ _______    ____      o                          ");
	put_str("         |[] [] []| [] [] [] [] [_____(__  ][]]_n_n__][.                        ");
	put_str("        _|________|_[_________]_[________]_|__|________)<                       ");
	put_str("         oo    oo 'oo      oo ' oo    oo 'oo 0000---oo\\_                        ");
	put_str("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	sleep(250);
	set_cursor(0, 0);
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                   TRAIN OF NEVER GONNA GIVE YOU                                ");
	put_str("                        |                                                       ");
	put_str("                        |                   o o                                 ");
	put_str("                       \\|/                      o o                             ");
	put_str("            _____                                   o                           ");
	put_str("          __|[_]|__ ___________ _______    ____      o                          ");
	put_str("         |[] [] []| [] [] [] [] [_____(__  ][]]_n_n__][.                        ");
	put_str("        _|________|_[_________]_[________]_|__|________)<                       ");
	put_str("         oo    oo 'oo      oo ' oo    oo 'oo 0000---oo\\_                        ");
	put_str("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	sleep(250);
	set_cursor(0, 0);
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                   TRAIN OF NEVER GONNA GIVE YOU U                              ");
	put_str("                        |                                                       ");
	put_str("                        |                   o o                                 ");
	put_str("                       \\|/                      o o                             ");
	put_str("            _____                                   o                           ");
	put_str("          __|[_]|__ ___________ _______    ____      o                          ");
	put_str("         |[] [] []| [] [] [] [] [_____(__  ][]]_n_n__][.                        ");
	put_str("        _|________|_[_________]_[________]_|__|________)<                       ");
	put_str("         oo    oo 'oo      oo ' oo    oo 'oo 0000---oo\\_                        ");
	put_str("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	sleep(250);
	set_cursor(0, 0);
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                   TRAIN OF NEVER GONNA GIVE YOU UP                             ");
	put_str("                        |                                                       ");
	put_str("                        |                   o o                                 ");
	put_str("                       \\|/                      o o                             ");
	put_str("            _____                                   o                           ");
	put_str("          __|[_]|__ ___________ _______    ____      o                          ");
	put_str("         |[] [] []| [] [] [] [] [_____(__  ][]]_n_n__][.                        ");
	put_str("        _|________|_[_________]_[________]_|__|________)<                       ");
	put_str("         oo    oo 'oo      oo ' oo    oo 'oo 0000---oo\\_                        ");
	put_str("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	put_str("                                                                                ");
	sleep(250);
	set_cursor(0, 0);
	clrs();}
}


int	main() {
	screen_init(1);
	//draw_weird();
	//cursor_mode(0);
	set_cursor(75, 24);
	//set_default_attr(get_attr(GREEN, BLACK, 0));
	put_str("s\rq");
	//u8 l = get_attr(BLUE, GRAY, 1);
	//put_nbr(l, HEX_FORMAT);
	//set_default_attr(l);
	//set_unset_blinking(1);
	//put_str("Helwfawfawff");
	return (5);
}
